### ISSUE TITLE
Question about your readme prerequisite

### ISSUE THREAD

**Issue by mesqueeb** [ReallySmallSoftware/cordova-plugin-firebaseui-auth#5]
My app can already launch succesfully in android simulator, but trying to get firebaseui authentication to work!

In your Readme you state that first we must "add android" to firebase app.
When I do this it says:
```
The Google services plugin for Gradle loads the google-services.json file that you just downloaded. Modify your build.gradle files to use the plugin.

Project-level build.gradle (<project>/build.gradle):

buildscript {
  dependencies {
    // Add this line
    classpath 'com.google.gms:google-services:4.0.1'
  }
}
```

Where in my cordova source files should I add this code?

**Comment by ReallySmallSoftware** [comment]
That message refers more to if you were writing a totally native app, so you shouldn't need to add that anywhere, preferring the approach of adding the cordova-support-google-services plugin instead.

If that doesn't give you a latest enough version then you can try editing the <project>/platforms/android/build.gradle file where you add the classpath line into the existing buildscript block.

I'm afraid it's always a case of trying to seeing what works - although I've done my best to make the plugins play nice the dependency management aspect of all the Google dependencies is always a little tricky.

**Comment by mesqueeb** [comment]
Thanks ! I’ll forget about this step for now!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
