### ISSUE TITLE
Silent Login

### ISSUE THREAD

**Issue by TaylorDale** [ReallySmallSoftware/cordova-plugin-firebaseui-auth#9]
Is there currently a way to silently sign the user in if they sign before? Pretty much the only way to do it at the moment is to call the login function which works after the first login, but not the first login as it interrupts the user.

Thanks for this - this seems to be the only Cordova extension that actually implements the real native Firebase SDK.

**Comment by ReallySmallSoftware** [comment]
You want to silently login as an anonymous user? signInAnonymously() should do that.

I'm not sure how you could silently login the first time as a real user without interrupting them.

Maybe I am misunderstanding something?

Anyway, glad you like the plugin.

**Comment by TaylorDale** [comment]
I'll rephrase - after the user logs in for the first time with the interface using signIn(), their session persists upon subsequent launches but only if you call signIn() again at launch.

Therefore as far as I know there is no way to persist a user session without calling signIn() automatically, which for persisting users is fine, but for first time users will present a login dialog.

May be expressed with psuedocode something like:

```
if (has_previous_session()) {
    silentsignin();
}

//otherwise user does not have a saved signin. 
// upon 'sign in' button press
signIn();
```

This is to avoid instantly prompting the user for a signin if they are a first time user of the app.

**Comment by ReallySmallSoftware** [comment]
OK,I understand better now. Thanks.

**Comment by ReallySmallSoftware** [comment]
@TaylorDale  I've add a method, getCurrentUser() which you may be able to use to determine whether a user had previously logged in and then if so fire the signIn() method which would then try and silently sign in. It *looked* like it was working when I tried it on my test app.

I also addressed an issue on iOS where the callback was being fired wrong if a login attempt failied.

**Comment by TaylorDale** [comment]
@ReallySmallSoftware  awesome, thanks for that!
